サブマニュアルを更新しました
aoyg/OfficeWorkManual pull request #1
Opened 2021-06-09 22:22 UTC by aoyg

サブマニュアルの項目を記入しました。問題がないか確認をお願いします。

2021-06-09 22:27 UTC, Naoyg requested changes

2021-06-09 22:27 UTC, Naoyg commented on sub_manual.md
> +Gmailアカウントはメールの送受信、社内文書の共有などで必要になります。
SMTPサーバーやポートの設定についてめお触れた方がよいのでは

2021-06-10 11:05 UTC, aoyg commented on sub_manual.md
> +Gmailアカウントはメールの送受信、社内文書の共有などで必要になります。
承知しました。本日中に修正します。

2021-06-10 11:09 UTC, aoyg commented
メール設定を加算してプッシュしました。再確認お願いします。

2021-06-10 11:10 UTC, Naoyg approved these changes

2021-06-10 11:11 UTC, merged